server {
    listen 80 default_server;
    listen 443 ssl default_server;
    server_name manuals.playstation.net manuals.sonyentertainmentnetwork.com _;

    ssl_certificate     /etc/ssl/certs/psh5jb.crt;
    ssl_certificate_key /etc/ssl/private/psh5jb.key;

    root /var/www/psh5;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
